name: Add Submodules

on:
  workflow_dispatch:

jobs:
  add-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add Gonerino submodule
        run: |
          git submodule add https://github.com/castdrian/Gonerino Tweaks/Gonerino
          git add .
          git commit -m "Added Gonerino submodule"
          git push origin

      - name: Make .bundle files
        run: |
          cd Bundles
          ln -s ../Tweaks/Gonerino/layout/Library/Application\ Support/Gonerino.bundle Gonerino.bundle
          git add .
          git commit -m "Added Gonerino bundle"
          git push origin

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
